# -*- coding: utf-8 -*-
"""Exercício_Modulo_2_aula_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g3xB5tOD3wLJ2pCY8SuUusq0_9RmPv2U
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Desafio 1 - Carregar os Dados
dados=pd.read_csv('arquivo_vendas.csv',delimiter=';')
print(dados.head(5))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dados=pd.read_csv('arquivo_vendas.csv',delimiter=';')


#Desafio 2 - Análise Exploratória de Dados:

print(f'\nResumo Estatístico:\n{dados.describe()}')

media_por_idade = dados.groupby('Idade').mean()
print(f'\nMédia por Idade:\n{media_por_idade}')

media_por_valor_compra = dados.groupby('Valor Compra').mean()
media_arrendodada = np.round(media_por_valor_compra)
print(f'\nMédia por Valor:\n{media_arrendodada}')

mediana_idade=dados['Idade'].median()
print(f'\nMediana de Idade:\n{mediana_idade}')

desvio_padrao_valor_compra=dados['Valor Compra'].std().round()
print(f'\nDesvio Padrão:\nd{desvio_padrao_valor_compra}')

print("\nDados faltantes por colunas:\n",dados.isnull().sum())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dados=pd.read_csv('arquivo_vendas.csv',delimiter=';')

#Desafio 3 - Manipulação e Limpeza dos Dados:

def faixa_etaria(idade):
    if idade < 30:
        return 'Jovem'
    elif idade >= 30 and idade < 65:
        return 'Adulto'
    else:
      return 'Idoso'

dados['Faixa Etária'] = dados['Idade'].apply(faixa_etaria)
print(dados.head())

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dados=pd.read_csv('arquivo_vendas.csv',delimiter=';')

def faixa_etaria(idade):
    if idade < 30:
        return 'Jovem'
    elif idade >= 30 and idade < 65:
        return 'Adulto'
    else:
      return 'Idoso'

dados['Faixa Etária'] = dados['Idade'].apply(faixa_etaria)

#Desafio 4 - Análise Detalhada:
itens_mais_vendidos = dados['Item Comprado'].value_counts()
categorias_populares = dados['Categoria'].value_counts()
print(f'\nContagem dos itens mais vendidos: \n{itens_mais_vendidos}')
print(f'\nCategorias mais populares:\n{categorias_populares}')

media_compra_por_idade = dados.groupby('Idade')['Valor Compra'].mean().reset_index().round(2)
print(f'\nValor médio por Idade\n{media_compra_por_idade}')

media_compra_por_cidade = dados.groupby('Cidade')['Valor Compra'].mean().reset_index().round(2)
print(f'\nValor médio por Idade\n{media_compra_por_cidade}')

preferencia_pagamento_idade = dados.groupby(['Método Pagamento','Faixa Etária']).size().unstack().fillna(0)
print(preferencia_pagamento_idade)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dados=pd.read_csv('arquivo_vendas.csv',delimiter=';')

#Desafio 5 - Visualização de Dados:

preferencia_pagamento_idade.plot(kind='bar')
plt.title('Preferência de Pagamento')
plt.ylabel('Método de Pagamento')
plt.xlabel('Faixa Etária')
plt.show()

itens_mais_vendidos.plot(kind='bar')
plt.title('Itens Mais Vendidos')
plt.ylabel('Quantidade')
plt.xlabel('Categoria')
plt.show()

itens_mais_vendidos.plot(kind='pie', autopct='%1.1f%%')
plt.title('Itens Mais Vendidos')
plt.xlabel('Categoria')
plt.show()

#Desafio 6 Insights e Conclusões:

# Insights:

# 1. Produtos Populares:
#    - Camisetas são os itens mais vendidos, enquanto calças jeans têm baixo desempenho.
#      A categoria "Agasalhos" é menos popular. Isso sugere uma oportunidade de promoção
#      ou marketing direcionado para impulsionar as vendas desses itens menos populares.

# 2. Perfil Demográfico de Compradores:
#    - A faixa etária de 53 e 49 anos é a que mais compra, seguida pela faixa de 44 anos.
#      Por outro lado, as faixas etárias de 48, 42 e 27 anos mostram menor atividade de compra.
#      A empresa pode adaptar suas estratégias de marketing para atender melhor às preferências
#      e necessidades das faixas etárias menos ativas.

# 3. Variação Geográfica nas Vendas:
#    - Sergipe, São Paulo e Tocantins são os estados com menor volume de vendas, enquanto Ceará,
#      Amapá e Alagoas têm desempenho superior. A empresa pode considerar estratégias regionais
#      específicas, como campanhas promocionais direcionadas ou parcerias locais, para impulsionar
#      as vendas nos estados com menor desempenho.

# 4. Preferências de Método de Pagamento:
#    - Cartão de crédito é o método de pagamento mais popular em todas as faixas etárias.
#      A empresa pode oferecer promoções ou benefícios específicos para clientes que utilizam
#      métodos de pagamento menos populares, incentivando a diversificação dos métodos de pagamento
#      e melhorando a experiência do cliente.

# Sugestões de Ações:

# 1. Campanhas Promocionais Específicas:
#    - Lançar campanhas promocionais para impulsionar as vendas de produtos menos populares,
#      como calças jeans e agasalhos. Isso pode incluir descontos especiais, pacotes promocionais
#      ou brindes.

# 2. Segmentação de Marketing por Faixa Etária:
#    - Personalizar estratégias de marketing para atender melhor às diferentes faixas etárias.
#      Isso pode envolver a criação de conteúdo específico, parcerias com influenciadores
#      relevantes para cada faixa etária e a oferta de produtos alinhados aos interesses de cada grupo.

# 3. Estratégias Regionais:
#    - Desenvolver estratégias de marketing específicas para estados com desempenho inferior,
#      considerando as características demográficas e culturais locais. Parcerias com empresas locais
#      e promoções adaptadas à região podem ser eficazes.

# 4. Incentivos para Diversificação de Pagamentos:
#    - Introduzir promoções ou descontos exclusivos para clientes que utilizam métodos de pagamento
#      menos populares, incentivando a diversificação e oferecendo uma experiência de compra mais flexível.