# -*- coding: utf-8 -*-
"""Modulo 2 - aula 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OB2P0O3xRCKf-MSZmiJLEKMrIH210GXy

> # Parte I
"""

import random

numero_de_respostas = 150
numeros = random.randint(0,10)
temperatura_inicial = 30
temperatura_final = 15

def multiplicação(x):
  conta = x * 5
  return conta;

lista = []
lista.append(numero_de_respostas)
lista.append(multiplicação(numeros))

if lista[1] > 15:
  print(f'O número {lista[1]} é maior que 15')
else:
  print(f'O número {lista[1]} não é menor que 15')

while temperatura_inicial > temperatura_final:
  temperatura_inicial = temperatura_inicial - 1;
  print(f'A temperatura está em {temperatura_inicial}º graus')

print(f'Dentro da minha lista tem os itens: {lista}')

pessoas = ['Luli', 'Lelo', 'Loui'], ['Lapras', 'Lepras']
lugar = 0

for lugares in pessoas :
  print(f'Lugar {lugar}: {lugares}')
  lugar+=1

print(pessoas[0][2])

class Carro:
  def __init__(self, marca, modelo, cor):
    self.marca = marca
    self.modelo = modelo
    self.cor = cor

  def descrever(self):
    return f"Carro: {self.marca}, {self.modelo}, {self.cor}"

carro_sonho = Carro('Maverick','Chevrolet','Preto')

print(carro_sonho.descrever())

"""# PARTE II"""

import numpy as np
import random

n1 = random.randint(0,10000)
n2 = random.randint(0,10000)
n3 = random.randint(0,10000)
n4 = random.randint(0,10000)
n5 = random.randint(0,10000)

array = np.array([n1,n2,n3,n4,n5])

print(f'Meu array: {array}')
print(f'Meu array multiplicado por 3: {array * 3}')
print(f'Meu array elevado ao quadrado: {array**2}')
print(f'A média do meu array: {array.mean()}')

"""# Parte III"""

import pandas as pd

dados = {
    'Nome' : ['Dwayne', 'Rock', 'Memphys'],
    'Idade' : [50, 49, 34],
    'Cidade' : ['Hawaí', 'Nashville', 'Dalla']
}

df = pd.DataFrame(dados)
print(df)

menor_50 = df[df['Idade'] < 50]
print(f'\nPessoas com menos de 50 anos: \n{menor_50}')

mora_no_interior = df[df['Cidade'] == 'Nashville']
print(f'\nPessoas que moram no interior: \n{mora_no_interior}')

df['Lucro'] = [19082, 47839, 139384]

salario = df[df['Lucro'] > 48000]
print(f'\nPessoas que ganham mais que $48000: \n {salario}')

media_salario = df['Lucro'].mean()
print(f'\nA média do salário é: {media_salario.round()}')

import matplotlib.pyplot as plt

nome=['Dwayne', 'Rock', 'Memphys', 'Lepras', 'Loli', 'Pop'],
idade=[50, 49, 34, 13, 18, 98]

##plt.bar(nome, idade)

plt.title("Nome e Idade em forma de Título")
plt.xlabel("Nome")
plt.ylabel("Idade")

plt.show()